# Environment Settings
workers: 4                        # (int) The number of workers processing the data.
seed: 2025                        # (int) Random seed.
state: INFO                       # (str) Logging level.
log_dir: ./logs/                  # (str) The path of logs.
model_dir: ./saved_models/        # (str) The path of saved models from Soul.
data_dir: ~/data/                 # (str) The path of input datasets.
sop: false                        # (bool) Energy cost simulation for neuromorphic chip

# Training Settings
epochs: 150                       # (int) The number of training epochs.
batch_size: 128                   # (int) The training batch size.
optimizer: adam                   # (str) The name of used optimizer.
scheduler: cosine                 # (str) The name of optimizer scheduler
learning_rate: 0.0001             # (float) Learning rate.
weight_decay: 0.0                 # (float) The weight decay value (L2 penalty) for optimizers.
momentum: 0.9                     # (float) inertia coefficient for optimizer

# Model Settings
model: spikingvgg9                # (str) The name of model to be used.
neuron_type: lif                  # (str) neuron model for SNNs
time_step: 4                     # (int) The number of time steps for SNNs.
dataset_name: cifar10             # (str) The name of dataset to be used.