# Environment Settings
is_distributed: false      # (bool) Whether to use distributed training.
workers: 4                       # (int) The number of workers processing the data.
seed: 42                       # (int) Random seed.
state: INFO                      # (str) Logging level.
log_dir: ./logs/                 # (str) The path of logs.
model_dir: ./saved_models/       # (str) The path of saved models from Soul.
data_dir: ./data/                # (str) The path of input datasets.
sop: False

# Training Settings
epochs: 150                      # (int) The number of training epochs.
batch_size: 128                  # (int) The training batch size.
optimizer: adam                  # (str) The name of used optimizer.
scheduler: cosine                # (str) The name of optimizer scheduler
learning_rate: 0.0001            # (float) Learning rate.
weight_decay: 0.0                # (float) The weight decay value (L2 penalty) for optimizers.
momentum: 0.9                    # (float) inertia coefficient for optimizer

# neuron
neuron_type: clif