v_threshold: 1.0            # (float) firing threshold for neuron
v_reset: 0.0                # (float) reset value for membrane potential
surrogate: quant            # (str) surrogate gradient function
detach_reset: true          # (bool) whether to detach reset from computation graph