v_threshold: 1.0              # (float) firing threshold for neuron
surrogate: atan               # (str) surrogate function for back-propagation
tau: 2.0
decay_input: true
v_reset: 0.0
detach_reset: true
store_v_seq: false