patch_size: 16                      # (int) patch size for input
mlp_ratio: 4                        # (float) expand ratio for hidden dimension in MLP intermediate layers
num_heads: 8                        # (int) number of heads for attention output