Network:
  epochs: 120
  batch_size: 64
  n_steps: 5
  dataset: "MNIST"
  rule: "TSSLBP"
  data_path: "/home/yudi/data"
  lr: 0.0005
  loss: "kernel"
  n_class: 10
  desired_count: 4
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:
  conv_1:
    type: "conv"
    in_channels: 1
    out_channels: 12
    kernel_size: 5
    weight_scale: 1
    padding: 0
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  conv_2:
    type: "conv"
    in_channels: 12
    out_channels: 64
    kernel_size: 5
    weight_scale: 1
    padding: 0
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2
    threshold: 1

  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    weight_scale: 1
    threshold: 1
