Network:
  epochs: 120
  batch_size: 50
  n_steps: 5
  dataset: "MNIST"
  rule: "TSSLBP"
  data_path: "./datasets/mnist"
  lr: 0.0005
  loss: "kernel"
  n_class: 10
  desired_count: 4
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:
  conv_1:
    type: "conv"
    in_channels: 1
    out_channels: 30
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  pooling_1: 
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_2: 
    type: "conv"
    in_channels: 30
    out_channels: 60
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  pooling_2: # 6
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_3: 
    type: "conv"
    in_channels: 60
    out_channels: 30
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 0.5

  output:
    type: "linear"
    n_inputs: 1470
    n_outputs: 10
    weight_scale: 1
    threshold: 1
