Network:
  epochs: 120
  batch_size: 50
  n_steps: 10
  dataset: "NMNIST_Spiking"
  rule: "TSSLBP"
  data_path: "./datasets/nmnist"
  lr: 0.0005
  loss: "count"
  n_class: 10
  desired_count: 15
  undesired_count: 3
  tau_m: 8
  tau_s: 4
  model: "LIF"

Layers:
  conv_1:
    type: "conv" 
    in_channels: 2
    out_channels: 30
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  pooling_1: 
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_2: 
    type: "conv"
    in_channels: 30
    out_channels: 60
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 1

  pooling_2: 
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_3: 
    type: "conv"
    in_channels: 60
    out_channels: 30
    kernel_size: 3
    weight_scale: 1
    padding: 1
    threshold: 0.5

  output:
    type: "linear"
    n_inputs: 1920
    n_outputs: 10
    weight_scale: 1
    threshold: 1

